# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with NPM
# For more information see: https://github.com/actions/setup-ruby

name: Ruby

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PVAULT_SERVICE_LICENSE: ${{ secrets.PVAULT_SERVICE_LICENSE }}
  PVAULT_API_KEY: ${{ secrets.PVAULT_API_KEY }}

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1.3']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/actions/setup-node#versioning):
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}

    - name: clean & generate-sdk
      run:
        make clean
        make generate-sdk
    - name: run tests
      run: make app-test
